plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'lib/tasks/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

# Increase line length for API responses and tests
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Allow longer methods in specs
Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'spec/**/*'

# Allow longer blocks in specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

# Rails-specific configurations
Rails:
  Enabled: true

# RSpec-specific configurations
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 4

Metrics/ParameterLists:
  Max: 6

# Style preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

RSpec/EmptyExampleGroup:
  Enabled: false

# Max memoized
RSpec/MultipleMemoizedHelpers:
  Max: 20

Rails/WhereRange:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Lint/EmptyBlock:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Rails/OrderArguments:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false